[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pikachu-chem"
version = "1.1.4"
description = "PIKACHU: Python-based Informatics Kit for Analysing CHemical Units"
readme = "README.md"
authors = [
  { name = "Barbara Terlouw", email = "barbara.terlouw@wur.nl" }
]
dependencies = ["matplotlib"]

[tool.setuptools.packages.find]
include = ["pikachu*"]
exclude = [
  "validation*",
  "example_scripts*",
  "example_images*",
  "example_structures*"
]